server:
  port: 8888 #\u7AEF\u53E3\u53F7\uFF0C\u9ED8\u8BA4\u4E0D\u5199\u5C31\u662F8080
  servlet:
    context-path: /mybatisplus #\u9879\u76EE\u4E0A\u4E0B\u6587,\u5FC5\u987B\u8981\u4EE5\u201C/\u201D\u5F00\u5934

spring:
  datasource:
    username: root #\u6570\u636E\u5E93\u7528\u6237\u540D
    password: root #\u6570\u636E\u5E93\u5BC6\u7801
    url: jdbc:mysql://localhost:3306/mybatis_plus_demo?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver #\u76F4\u63A5\u6253mysql\u4F1A\u6709\u63D0\u793A

#showSql\u65E5\u5FD7\u8F93\u51FA\uFF0C\u6839\u636E\u81EA\u5DF1\u7684\u5305\u540D\u8FDB\u884C\u4FEE\u6539
logging:
  level:
    com:
      zbs:
        mybatisplus:
          dao: debug
